// <auto-generated />
namespace Harvestly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TruYumContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TruYumContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202006221147204_TruYumContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
